### ISSUE TITLE
support C++？

### ISSUE THREAD

**Issue by Colbert337** [xoreaxeaxeax/movfuscator#17]
Dear sir，
Do you have any plans to support C++?

thx a lot!

**Comment by nullableVoidPtr** [comment]
https://github.com/xoreaxeaxeax/movfuscator/blob/master/README.md#other-source-languages 

_Sent from my Xiaomi Redmi 4X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tpruzina** [comment]
Difficulty of implementing C++ compiler when compared to tiny language as C is quite massive, I don't see it happening in current state of the project. It would be probably easier to create a new project and take some known compiler (gcc,clang) and merely rewrite backend to generate mov code instead of x86.

I just don't see xoreaxeaxeax spending huge ammount of time on that, but then again I didn't see this project coming out either.

**Comment by bit2shift** [comment]
It would be better if movfuscator acted more like an x86 &rightarrow; x86 translator rather than an actual C compiler.

**Comment by xoreaxeaxeax** [comment]
No plans to support C++; since the frontend only supports C, it would need a complete rewrite for an entirely different frontend.
